name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: build image
        run: |
            IMAGE_TAG=${GITHUB_SHA::8}   # short SHA
            IMAGE_NAME=${{ steps.login-ecr.outputs.registry }}/app-portfolio
            echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
            echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
            docker build -t $IMAGE_NAME:$IMAGE_TAG .
            docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
        env:
            AWS_REGION: ${{ env.AWS_REGION }}
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}  # use evaluated env variables
          format: table
          exit-code: 1
          vuln-type: "os,library"
      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 \
              | docker login --username AWS --password-stdin 313715282743.dkr.ecr.us-east-1.amazonaws.com
            docker rm -f resume || true
            docker run -d --name resume -p 8080:5001 \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/app-portfolio:${{ github.run_number }}
